# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore BackEnd/keyboard-warrior.sln
    - name: Build 
      run: dotnet build BackEnd/keyboard-warrior.sln --no-restore

    - name: Start application
      run: dotnet run --project BackEnd/keyboard-warrior/keyboard-warrior.csproj & # Asegúrate de que el puerto coincida con tus pruebas

    # 6. Esperar que la aplicación inicie
    - name: Wait for application to start
      run: |
        echo "Waiting for app to start..."
        sleep 10  # Ajusta el tiempo si tu app tarda más en arrancar
        
    - name: Test
      run: dotnet test BackEnd/keyboard-warrior.sln --no-build --verbosity normal
