# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore prueba-actions/BackEnd/Keyboard-warrior
    - name: Build 
      run: dotnet build prueba-actions/BackEnd/Keyboard-warrior --no-restore
    - name: Test
      run: dotnet test prueba-actions/BackEnd/Keyboard-warrior.Test --no-build --verbosity normal
